version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.2
jobs:
  install-chrome:
    executor: browser-tools/default
    steps:
      - browser-tools/install-browser-tools:
          chrome-version: 87.0.4280.88
  build:
    docker:
      - image: cimg/openjdk:8.0-browsers
    steps:
      - checkout
      - run: mvn verify
workflows:
  install_and_test:
    jobs:
      - install-chrome
      - build:
        requires:
          - install-chrome
