version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.2
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0-browsers
    steps:
      - browser-tools/install-browser-tools:
          chrome-version: 87.0.4280.88      
      - checkout
      - run: mvn verify
      - store_artifacts:
          path: ./target/site/allure-maven-plugin/